// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VillagerBot.Data;

#nullable disable

namespace VillagerBot.Data.Migrations
{
    [DbContext(typeof(VillagerBotDbContext))]
    partial class VillagerBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("queue_position");

            modelBuilder.Entity("VillagerBot.Data.ActiveRequest", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long?>("HunterId")
                        .HasColumnType("bigint")
                        .HasColumnName("hunter_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateTimeOffset?>("PulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pulled_at");

                    b.Property<long>("QueuePosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("queue_position")
                        .HasDefaultValueSql("nextval('queue_position')");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("VillagerKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("villager_key");

                    b.HasKey("UserId")
                        .HasName("pk_active_requests");

                    b.HasIndex("ChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_active_requests_channel_id");

                    b.HasIndex("QueuePosition")
                        .IsUnique()
                        .HasDatabaseName("ix_active_requests_queue_position");

                    b.HasIndex("VillagerKey")
                        .HasDatabaseName("ix_active_requests_villager_key");

                    b.HasIndex("PulledAt", "IsAvailable", "QueuePosition")
                        .HasDatabaseName("ix_active_requests_pulled_at_is_available_queue_position");

                    b.ToTable("active_requests", (string)null);
                });

            modelBuilder.Entity("VillagerBot.Data.ArchivedRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long?>("HunterId")
                        .HasColumnType("bigint")
                        .HasColumnName("hunter_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("PulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pulled_at");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("VillagerKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("villager_key");

                    b.HasKey("Id")
                        .HasName("pk_archived_requests");

                    b.HasIndex("VillagerKey")
                        .HasDatabaseName("ix_archived_requests_villager_key");

                    b.HasIndex("Outcome", "ClosedAt")
                        .HasDatabaseName("ix_archived_requests_outcome_closed_at");

                    b.HasIndex("UserId", "ClosedAt")
                        .HasDatabaseName("ix_archived_requests_user_id_closed_at");

                    b.ToTable("archived_requests", (string)null);
                });

            modelBuilder.Entity("VillagerBot.Data.BotStateEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_bot_state");

                    b.ToTable("bot_state", (string)null);
                });

            modelBuilder.Entity("VillagerBot.Data.OverflowCategory", b =>
                {
                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("CategoryId")
                        .HasName("pk_overflow_categories");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_overflow_categories_number");

                    b.ToTable("overflow_categories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
